app:
  name: 'go-comment-api'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-comment-api'

postgres:
  URL: 'postgres://okan:okan1905@localhost:5432/postgres'
  pool_max: 2

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'
